server:
  port: 8888

spring:
  application:
    name: restaurant-system-config-server
  main:
    banner-mode: off
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/local-repo
          order: 100
      allow-override: true
      override-none: false
      override-system-properties: true
encrypt:
  key: 1h1i1hiasdh1iiy87y8y8uy78ijahsbsxbjahuaO21Iccvv2e23H1eeH2yrfa1298a12ww111ssq11GT1132322FxFcD