server:
  port: 8888

spring:
  application:
    name: restaurant-system-config-server
  main:
    banner-mode: off
  profiles:
    active: git,native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codehub-learn/java-path-spring-cloud-standalone-config-showcase.git
          refresh-rate: 30
          default-label: main
          clone-on-start: true
          timeout: 5
          force-pull: true
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_ACCESS_TOKEN}
          order: 1
        native:
          search-locations: file:///${user.home}/local-repo
          order: 100
      allow-override: true #Later sources can override earlier ones
      override-none: false #Overrides are allowed
      override-system-properties: true #Config Server beats JVM args
#  curl -X POST http://localhost:8888/encrypt -H "Content-Type: text/plain" -d '...';
encrypt:
  key: 1h1i1hiasdh1iiy87y8y8uy78ijahsbsxbjahuaO21Iccvv2e23H1eeH2yrfa1298a12ww111ssq11GT1132322FxFcD